
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: hotel-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets                                 
