apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.appName}}
  name: {{.Values.appName}}
  namespace: {{.Values.namespace}}
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{.Values.appName}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
      - image: "{{.Values.image.repository}}:{{.Values.image.imageTag}}"
        imagePullPolicy: IfNotPresent
        name: {{.Values.namespace}}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: RDSHOST
          value: {{.Values.rdsHost}}
        - name: USERNAME
          value: {{.Values.username}}
        - name: RDSPASSWORD
          value: {{.Values.rdsPassword}}
        - name: PORT
          value: {{.Values.portOfRds | default 80 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler