apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: hotel-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: my-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: {{.Values.secretName}}
        property: username
    - secretKey: db-password
      remoteRef:
        key: {{.Values.secretName}}
        property: password
    - secretKey: db-endpoint
      remoteRef:
        key: {{.Values.secretName}}
        property: host
    - secretKey: db-port
      remoteRef:
        key: {{.Values.secretName}}
        property: port
